language: php
php:
    - 8.0

before_install:
  # turn off XDebug
  - phpenv config-rm xdebug.ini || return 0

install:
  # Composer
  - travis_retry composer install --no-progress --prefer-dist

script:
  # Nette/Tester
  - composer run-script test

jobs:
  include:

    - env: title="Lowest Dependencies 8.0"
      php: 8.0
      install:
        - travis_retry composer update --no-progress --prefer-dist --prefer-lowest
      script:
        - composer run-script test

    - stage: Phpstan
      php: 8.0
      script:
        - composer run-script phpstan

  allow_failures:
    - stage: Phpstan

after_failure:
  # Print *.actual content
  - for i in $(find tests -name \*.actual); do echo "--- $i"; cat $i; echo; echo; done

sudo: false

cache:
  directories:
    - $HOME/.composer/cache
